config/routes.rb
Rails.application.routes.draw do

  resources :attachments

  resources :products
  devise_for :users
  resources :in_shopping_carts, only:[:create,:destroy]

  post "/email/create", as: :create_email

  get "/carrito", to: "shopping_carts#show"
  post "/add/:product_id", as: :add_to_cart, to: "in_shopping_carts#create"
  post "/pagar", to: "payments#create"

  get "/checkout", to: "payments#checkout"

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def unregistered
  	render layout: "landing"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.haml
%h1 Bienvenido
%p
	=link_to "Cerrar sesión", destroy_user_session_path, method: :delete

app/views/welcome/unregistered.haml
%header.green.big-padding
	.col-md-10.no-float.center-block
		.col-md-6.no-padding.inline-block
			=image_tag "tiendus.png",width:"100"
			%h1.white-text.ultra-big.kostic
				%strong
					Ofrece tus prodcutos digitales a la audiencia
		.col-md-5.inline-block
			=image_tag "mono.png"


.grey.white-text.big-padding{style:"margin-top:5em;"}
	.col-md-10.no-float.center-block
		.absolute{style:"bottom:-4.5em;width:100%;left:0px;"}
			.text-center.big
				.col-md-3.inline-block
					.white.grey-text.circle
						%strong 1
				.col-md-3.inline-block
					.white.grey-text.circle
						%strong 2
				.col-md-3.inline-block
					.white.grey-text.circle
						%strong 3


		%h2.bigger.kostic.text-center 
			%strong
				Tiendus en 3 pasos
		.text-center.top-space
			.col-md-3.inline-block.text-left
				=image_tag "upload-icon.png",class:"col-md-10 inline-block"
				.top-space
					%strong.medium
						Sube tus archivos a Tiendus
					%p.white-text.text-justify.small
						¡Libro digital, canción, comic, cursos
						o lo que se te ocurra! Si lo puedes
						meter en un .Zip lo puedes vender.*
			.col-md-3.inline-block.text-left
				=image_tag "youtube-icon.png",class:"col-md-10 inline-block"
				.top-space
					%strong.medium
						Cuéntale a tus fans
					%p.white-text.text-justify.small
						Comparte el link personalizado de
						tu producto en tus redes sociales
						o sitio web. 
			.col-md-3.inline-block.text-left
				=image_tag "money-icon.png",class:"col-md-10 inline-block"
				.top-space
					%strong.medium
						Vende y gana dinero
					%p.white-text.text-justify.small
						Recibe tu dinero en tu cuenta de PayPal
						y tu cliente su producto en su email
						inmediatamente. Así de fácil.

.red.white-text.big-padding.kostic{style:"margin-top:5em;"}
	.col-md-8.no-float.text-center.center-block
		=image_tag "media-icons.png"
		%p.medium.col-md-11.center-block.no-float.top-space
			%strong
				Vende tus libros electrónicos, tutoriales, canciones, comics, plantillas, fotografías de stock, archivos fuente, ¡cualquier producto digital!	
.top-space.big-padding.bottom-space
	.col-md-11.col-xs-12.center-block.no-float
		=form_tag(create_email_path,method: :post, remote: true,id: "emails_form") do
			=email_field_tag "email",nil,class:"col-xs-12 inline-block text-center landing-form",placeholder:"Escribe aquí tu mail"
		#email-info.red.white-text.large-padding